/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Atomically replaces the assigned value of the given key by the specified value using a custom
 * javax.cache.expiry.ExpiryPolicy and returns the previously assigned value. If the cache is configured for
 * write-through operation mode, the underlying configured javax.cache.integration.CacheWriter might be called to
 * store the value of the key to any kind of external resource.
 */
//@Generated("04e83de84c422d3550c33863903966b1")
const (
    //hex: 0x130B00
    CacheGetAndReplaceRequestMessageType = 1248000
    //hex: 0x130B01
    CacheGetAndReplaceResponseMessageType = 1248001
    CacheGetAndReplaceRequestCompletionIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    CacheGetAndReplaceRequestInitialFrameSize = CacheGetAndReplaceRequestCompletionIdFieldOffset + bufutil.IntSizeInBytes
    CacheGetAndReplaceResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type CacheGetAndReplaceRequestParameters struct {

    /**
    * Name of the cache.
    */
name string

    /**
    * The key whose value is replaced.
    */
key serialization.Data

    /**
    * The new value to be associated with the specified key.
    */
value serialization.Data

    /**
    * Expiry policy for the entry. Byte-array which is serialized from an object implementing
    * javax.cache.expiry.ExpiryPolicy interface.
    */
/* @Nullable */ expiryPolicy serialization.Data

    /**
    * User generated id which shall be received as a field of the cache event upon completion of
    * the request in the cluster.
    */
completionId int
}

func CacheGetAndReplaceEncodeRequest(name string, key serialization.Data, value serialization.Data, /* @Nullable */ expiryPolicy serialization.Data, completionId int) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Cache.GetAndReplace")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, CacheGetAndReplaceRequestMessageType)
    bufutil.EncodeInt(initialFrame.Content, CacheGetAndReplaceRequestCompletionIdFieldOffset, completionId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    DataCodec.encode(clientMessage, value)
    CodecUtil.encodeNullable(clientMessage, expiryPolicy, DataCodecEncode)
    return clientMessage
}

func CacheGetAndReplaceDecodeRequest(clientMessage *bufutil.ClientMessagex) *CacheGetAndReplaceRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(CacheGetAndReplaceRequestParameters)
    initialFrame := iterator.Next()
    request.completionId = bufutil.DecodeInt(initialFrame.Content, CacheGetAndReplaceRequestCompletionIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    request.value = DataCodec.decode(iterator)
    request.expiryPolicy = CodecUtil.decodeNullable(iterator, DataCodecDecode) 
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type CacheGetAndReplaceResponseParameters struct {
    /**
    * The old value previously assigned to the given key.
    */
/* @Nullable */ response serialization.Data
}

func CacheGetAndReplaceEncodeResponse(/* @Nullable */ response serialization.Data ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, CacheGetAndReplaceResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, CacheGetAndReplaceResponseMessageType)
    clientMessage.Add(initialFrame)

    CodecUtil.encodeNullable(clientMessage, response, DataCodecEncode)
    return clientMessage
}

func CacheGetAndReplaceDecodeResponse(clientMessage *bufutil.ClientMessagex) *CacheGetAndReplaceResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(CacheGetAndReplaceResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = CodecUtil.decodeNullable(iterator, DataCodecDecode) 
    return response
}

