/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Makes an authentication request to the cluster using custom credentials.
 */
//@Generated("2c69a46adcc342b094dc3c2326e9077f")
const (
    //hex: 0x000200
    ClientAuthenticationCustomRequestMessageType = 512
    //hex: 0x000201
    ClientAuthenticationCustomResponseMessageType = 513
    ClientAuthenticationCustomRequestUuidFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ClientAuthenticationCustomRequestSerializationVersionFieldOffset = ClientAuthenticationCustomRequestUuidFieldOffset + bufutil.UUIDSizeInBytes
    ClientAuthenticationCustomRequestInitialFrameSize = ClientAuthenticationCustomRequestSerializationVersionFieldOffset + bufutil.ByteSizeInBytes
    ClientAuthenticationCustomResponseStatusFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    ClientAuthenticationCustomResponseUuidFieldOffset = ClientAuthenticationCustomResponseStatusFieldOffset + bufutil.ByteSizeInBytes
    ClientAuthenticationCustomResponseSerializationVersionFieldOffset = ClientAuthenticationCustomResponseUuidFieldOffset + bufutil.UUIDSizeInBytes
    ClientAuthenticationCustomResponsePartitionCountFieldOffset = ClientAuthenticationCustomResponseSerializationVersionFieldOffset + bufutil.ByteSizeInBytes
    ClientAuthenticationCustomResponseClusterIdFieldOffset = ClientAuthenticationCustomResponsePartitionCountFieldOffset + bufutil.IntSizeInBytes
    ClientAuthenticationCustomResponseFailoverSupportedFieldOffset = ClientAuthenticationCustomResponseClusterIdFieldOffset + bufutil.UUIDSizeInBytes
    ClientAuthenticationCustomResponseInitialFrameSize = ClientAuthenticationCustomResponseFailoverSupportedFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ClientAuthenticationCustomRequestParameters struct {

    /**
    * Cluster name that client will connect to.
    */
clusterName string

    /**
    * Secret byte array for authentication.
    */
credentials []byte

    /**
    * Unique string identifying the connected client uniquely.
    */
/* @Nullable */ uuid string

    /**
    * The type of the client. E.g. JAVA, CPP, CSHARP, etc.
    */
clientType string

    /**
    * client side supported version to inform server side
    */
serializationVersion byte

    /**
    * The Hazelcast version of the client. (e.g. 3.7.2)
    */
clientHazelcastVersion string

    /**
    * the name of the client instance
    */
clientName string

    /**
    * User defined labels of the client instance
    */
labels []string
}

func ClientAuthenticationCustomEncodeRequest(clusterName string, credentials []byte, /* @Nullable */ uuid string, clientType string, serializationVersion byte, clientHazelcastVersion string, clientName string, labels []string) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = true
    clientMessage.SetOperationName("Client.AuthenticationCustom")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ClientAuthenticationCustomRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, ClientAuthenticationCustomRequestUuidFieldOffset, uuid)
    bufutil.EncodeByte(initialFrame.Content, ClientAuthenticationCustomRequestSerializationVersionFieldOffset, serializationVersion)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, clusterName)
    bufutil.ByteArrayCodecEncode(clientMessage, credentials)
    bufutil.StringCodecEncode(clientMessage, clientType)
    bufutil.StringCodecEncode(clientMessage, clientHazelcastVersion)
    bufutil.StringCodecEncode(clientMessage, clientName)
    clientMessage.Add(bufutil.BeginFrame)
        for i := 0; i < len(labels) ; i++ {
            bufutil.StringCodecEncode(clientMessage, labels[i])
        }
        clientMessage.Add(bufutil.EndFrame)


    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ClientAuthenticationCustomResponseParameters struct {
    /**
    * A byte that represents the authentication status. It can be AUTHENTICATED(0), CREDENTIALS_FAILED(1),
    * SERIALIZATION_VERSION_MISMATCH(2) or NOT_ALLOWED_IN_CLUSTER(3).
    */
status byte
    /**
    * Address of the Hazelcast member which sends the authentication response.
    */
/* @Nullable */ address Address
    /**
    * Unique string identifying the connected client uniquely.
    */
/* @Nullable */ uuid string
    /**
    * client side supported version to inform server side
    */
serializationVersion byte
    /**
    * Version of the Hazelcast member which sends the authentication response.
    */
serverHazelcastVersion string
    /**
    * Partition count of the cluster.
    */
partitionCount int32
    /**
    * The cluster id of the cluster.
    */
clusterId string
    /**
    * Returns true if server supports clients with failover feature.
    */
failoverSupported bool
}



func ClientAuthenticationCustomDecodeResponse(clientMessage *bufutil.ClientMessage) *ClientAuthenticationCustomResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ClientAuthenticationCustomResponseParameters)
    initialFrame := iterator.Next()
    response.status = bufutil.DecodeByte(initialFrame.Content, ClientAuthenticationCustomResponseStatusFieldOffset)
    response.uuid = bufutil.DecodeUUID(initialFrame.Content, ClientAuthenticationCustomResponseUuidFieldOffset)
    response.serializationVersion = bufutil.DecodeByte(initialFrame.Content, ClientAuthenticationCustomResponseSerializationVersionFieldOffset)
    response.partitionCount = bufutil.DecodeInt(initialFrame.Content, ClientAuthenticationCustomResponsePartitionCountFieldOffset)
    response.clusterId = bufutil.DecodeUUID(initialFrame.Content, ClientAuthenticationCustomResponseClusterIdFieldOffset)
    response.failoverSupported = bufutil.DecodeBoolean(initialFrame.Content, ClientAuthenticationCustomResponseFailoverSupportedFieldOffset)
    response.address =          bufutil.DecodeNullable(iterator, AddressCodecDecode).(Address)  
    response.serverHazelcastVersion = bufutil.StringCodecDecode(iterator)
    return response
}

