
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Proxies will be created on all cluster members.
 * If the member is  a lite member, a replicated map will not be created.
 * Any proxy creation failure is logged on the server side.
 * Exceptions related to a proxy creation failure is not send to the client.
 * A proxy creation failure does not cancel this operation, all proxies will be attempted to be created.
 */
//@Generated("6e67f6a3542d4092ebc58c3993030295")
const (
    //hex: 0x000E00
    ClientCreateProxiesRequestMessageType = 3584
    //hex: 0x000E01
    ClientCreateProxiesResponseMessageType = 3585
    ClientCreateProxiesRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    ClientCreateProxiesResponseInitialFrameSize = CorrelationIdFieldOffset + IntSizeInBytes

)

func ClientCreateProxiesEncodeRequest(proxies []*Pair) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Client.CreateProxies")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, ClientCreateProxiesRequestMessageType)
    clientMessage.Add(initialFrame)

            clientMessage.Add(BeginFrame.Copy())

        for _, cp := range proxies{
           StringCodecEncode(clientMessage, (*cp).Key().(string))
           StringCodecEncode(clientMessage, (*cp).Value().(string))
        }

        clientMessage.Add(EndFrame.Copy())



    return clientMessage
}


func ClientCreateProxiesDecodeResponse(clientMessage *ClientMessage) func() () {
    return func() () {
        iterator := clientMessage.FrameIterator()
        //empty initial frame
        iterator.Next()
        return
    }
}

