/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * TODO DOC
 */
//@Generated("d14c913169d6cf5e1c69b8186920383e")
const (
    //hex: 0x160300
    ContinuousQueryMadePublishableRequestMessageType = 1442560
    //hex: 0x160301
    ContinuousQueryMadePublishableResponseMessageType = 1442561
    ContinuousQueryMadePublishableRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ContinuousQueryMadePublishableResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    ContinuousQueryMadePublishableResponseInitialFrameSize = ContinuousQueryMadePublishableResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ContinuousQueryMadePublishableRequestParameters struct {

    /**
    * Name of the map.
    */
mapName string

    /**
    * Name of query cache.
    */
cacheName string
}

func ContinuousQueryMadePublishableEncodeRequest(mapName string, cacheName string) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("ContinuousQuery.MadePublishable")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ContinuousQueryMadePublishableRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, mapName)
    StringCodec.encode(clientMessage, cacheName)
    return clientMessage
}

func ContinuousQueryMadePublishableDecodeRequest(clientMessage *bufutil.ClientMessagex) *ContinuousQueryMadePublishableRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(ContinuousQueryMadePublishableRequestParameters)
    //empty initial frame
    iterator.Next()
    request.mapName = StringCodec.decode(iterator)
    request.cacheName = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ContinuousQueryMadePublishableResponseParameters struct {
    /**
    * True if successfully set as publishable, false otherwise.
    */
response bool
}

func ContinuousQueryMadePublishableEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, ContinuousQueryMadePublishableResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ContinuousQueryMadePublishableResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, ContinuousQueryMadePublishableResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func ContinuousQueryMadePublishableDecodeResponse(clientMessage *bufutil.ClientMessagex) *ContinuousQueryMadePublishableResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ContinuousQueryMadePublishableResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, ContinuousQueryMadePublishableResponseResponseFieldOffset)
    return response
}

