/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the current round. A round completes when the count value
 * reaches to 0 and a new round starts afterwards.
 */
//@Generated("efadde8fd3f6c3497bbf981fa69f3b1e")
const (
    //hex: 0x0B0500
    CountDownLatchGetRoundRequestMessageType = 722176
    //hex: 0x0B0501
    CountDownLatchGetRoundResponseMessageType = 722177
    CountDownLatchGetRoundRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    CountDownLatchGetRoundResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    CountDownLatchGetRoundResponseInitialFrameSize = CountDownLatchGetRoundResponseResponseFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type CountDownLatchGetRoundRequestParameters struct {

    /**
    * CP group id of this CountDownLatch instance
    */
groupId RaftGroupId

    /**
    * Name of the CountDownLatch instance
    */
name string
}

func CountDownLatchGetRoundEncodeRequest(groupId RaftGroupId, name string) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("CountDownLatch.GetRound")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, CountDownLatchGetRoundRequestMessageType)
    clientMessage.Add(initialFrame)
    RaftGroupIdCodec.encode(clientMessage, groupId)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func CountDownLatchGetRoundDecodeRequest(clientMessage *bufutil.ClientMessagex) *CountDownLatchGetRoundRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(CountDownLatchGetRoundRequestParameters)
    //empty initial frame
    iterator.Next()
    request.groupId = RaftGroupIdCodec.decode(iterator)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type CountDownLatchGetRoundResponseParameters struct {
    /**
    * The current round of this CountDownLatch instance
    */
response int
}

func CountDownLatchGetRoundEncodeResponse(response int ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, CountDownLatchGetRoundResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, CountDownLatchGetRoundResponseMessageType)
    bufutil.EncodeInt(initialFrame.Content, CountDownLatchGetRoundResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func CountDownLatchGetRoundDecodeResponse(clientMessage *bufutil.ClientMessagex) *CountDownLatchGetRoundResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(CountDownLatchGetRoundResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeInt(initialFrame.Content, CountDownLatchGetRoundResponseResponseFieldOffset)
    return response
}

