/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds a new cardinality estimator configuration to a running cluster.
 * If a cardinality estimator configuration with the given {@code name} already exists, then
 * the new configuration is ignored and the existing one is preserved.
 */
//@Generated("f8201c71432864400a486cc42a93337b")
const (
    //hex: 0x1B0300
    DynamicConfigAddCardinalityEstimatorConfigRequestMessageType = 1770240
    //hex: 0x1B0301
    DynamicConfigAddCardinalityEstimatorConfigResponseMessageType = 1770241
    DynamicConfigAddCardinalityEstimatorConfigRequestBackupCountFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    DynamicConfigAddCardinalityEstimatorConfigRequestAsyncBackupCountFieldOffset = DynamicConfigAddCardinalityEstimatorConfigRequestBackupCountFieldOffset + bufutil.IntSizeInBytes
    DynamicConfigAddCardinalityEstimatorConfigRequestMergeBatchSizeFieldOffset = DynamicConfigAddCardinalityEstimatorConfigRequestAsyncBackupCountFieldOffset + bufutil.IntSizeInBytes
    DynamicConfigAddCardinalityEstimatorConfigRequestInitialFrameSize = DynamicConfigAddCardinalityEstimatorConfigRequestMergeBatchSizeFieldOffset + bufutil.IntSizeInBytes
    DynamicConfigAddCardinalityEstimatorConfigResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type DynamicConfigAddCardinalityEstimatorConfigRequestParameters struct {

    /**
    * name of the cardinality estimator configuration
    */
name string

    /**
    * number of synchronous backups
    */
backupCount int

    /**
    * number of asynchronous backups
    */
asyncBackupCount int

    /**
    * name of an existing configured split brain protection to be used to determine the minimum number of members
    * required in the cluster for the lock to remain functional. When {@code null}, split brain protection does not
    * apply to this lock configuration's operations.
    */
/* @Nullable */ splitBrainProtectionName string

    /**
    * TODO DOC
    */
mergePolicy string

    /**
    * TODO DOC
    */
mergeBatchSize int
}

func DynamicConfigAddCardinalityEstimatorConfigEncodeRequest(name string, backupCount int, asyncBackupCount int, /* @Nullable */ splitBrainProtectionName string, mergePolicy string, mergeBatchSize int) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("DynamicConfig.AddCardinalityEstimatorConfig")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, DynamicConfigAddCardinalityEstimatorConfigRequestMessageType)
    bufutil.EncodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestBackupCountFieldOffset, backupCount)
    bufutil.EncodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestAsyncBackupCountFieldOffset, asyncBackupCount)
    bufutil.EncodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestMergeBatchSizeFieldOffset, mergeBatchSize)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    CodecUtil.encodeNullable(clientMessage, splitBrainProtectionName, StringCodecEncode)
    StringCodec.encode(clientMessage, mergePolicy)
    return clientMessage
}

func DynamicConfigAddCardinalityEstimatorConfigDecodeRequest(clientMessage *bufutil.ClientMessagex) *DynamicConfigAddCardinalityEstimatorConfigRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(DynamicConfigAddCardinalityEstimatorConfigRequestParameters)
    initialFrame := iterator.Next()
    request.backupCount = bufutil.DecodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestBackupCountFieldOffset)
    request.asyncBackupCount = bufutil.DecodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestAsyncBackupCountFieldOffset)
    request.mergeBatchSize = bufutil.DecodeInt(initialFrame.Content, DynamicConfigAddCardinalityEstimatorConfigRequestMergeBatchSizeFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.splitBrainProtectionName = CodecUtil.decodeNullable(iterator, StringCodecDecode) 
    request.mergePolicy = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type DynamicConfigAddCardinalityEstimatorConfigResponseParameters struct {
}

func DynamicConfigAddCardinalityEstimatorConfigEncodeResponse() *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, DynamicConfigAddCardinalityEstimatorConfigResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, DynamicConfigAddCardinalityEstimatorConfigResponseMessageType)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func DynamicConfigAddCardinalityEstimatorConfigDecodeResponse(clientMessage *bufutil.ClientMessagex) *DynamicConfigAddCardinalityEstimatorConfigResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(DynamicConfigAddCardinalityEstimatorConfigResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

