/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the element at the specified position in this list
 */
//@Generated("343ee3707ba314e8b327bff263466297")
const (
    //hex: 0x050F00
    ListGetRequestMessageType = 331520
    //hex: 0x050F01
    ListGetResponseMessageType = 331521
    ListGetRequestIndexFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ListGetRequestInitialFrameSize = ListGetRequestIndexFieldOffset + bufutil.IntSizeInBytes
    ListGetResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ListGetRequestParameters struct {

    /**
    * Name of the List
    */
name string

    /**
    * Index of the element to return
    */
index int
}

func ListGetEncodeRequest(name string, index int) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("List.Get")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ListGetRequestMessageType)
    bufutil.EncodeInt(initialFrame.Content, ListGetRequestIndexFieldOffset, index)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func ListGetDecodeRequest(clientMessage *bufutil.ClientMessagex) *ListGetRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(ListGetRequestParameters)
    initialFrame := iterator.Next()
    request.index = bufutil.DecodeInt(initialFrame.Content, ListGetRequestIndexFieldOffset)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ListGetResponseParameters struct {
    /**
    * The element at the specified position in this list
    */
/* @Nullable */ response serialization.Data
}

func ListGetEncodeResponse(/* @Nullable */ response serialization.Data ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, ListGetResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ListGetResponseMessageType)
    clientMessage.Add(initialFrame)

    CodecUtil.encodeNullable(clientMessage, response, DataCodecEncode)
    return clientMessage
}

func ListGetDecodeResponse(clientMessage *bufutil.ClientMessagex) *ListGetResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ListGetResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = CodecUtil.decodeNullable(iterator, DataCodecDecode) 
    return response
}

