/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns an iterator over the elements in this list in proper sequence.
 */
//@Generated("51412730b5535e6ab54ea8f6b0bf3236")
const (
    //hex: 0x051600
    ListIteratorRequestMessageType = 333312
    //hex: 0x051601
    ListIteratorResponseMessageType = 333313
    ListIteratorRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ListIteratorResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ListIteratorRequestParameters struct {

    /**
    * Name of the List
    */
name string
}

func ListIteratorEncodeRequest(name string) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("List.Iterator")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ListIteratorRequestMessageType)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    return clientMessage
}




/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ListIteratorResponseParameters struct {
    /**
    * An iterator over the elements in this list in proper sequence
    */
response []serialization.Data
}



func ListIteratorDecodeResponse(clientMessage *bufutil.ClientMessagex) *ListIteratorResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ListIteratorResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = bufutil.ListMultiFrameCodecDecode(iterator, bufutil.DataCodecDecode)
    return response
}

