
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the number of key-value mappings in this map.  If the map contains more than Integer.MAX_VALUE elements,
 * returns Integer.MAX_VALUE
 */
//@Generated("cdfda061eaef302e8468efcfee326229")
const (
    //hex: 0x012A00
    MapSizeRequestMessageType = 76288
    //hex: 0x012A01
    MapSizeResponseMessageType = 76289
    MapSizeRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    MapSizeResponseResponseFieldOffset = CorrelationIdFieldOffset + IntSizeInBytes
    MapSizeResponseInitialFrameSize = MapSizeResponseResponseFieldOffset + IntSizeInBytes

)

func MapSizeEncodeRequest(name string) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( true )
    clientMessage.SetOperationName("Map.Size")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MapSizeRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)

    return clientMessage
}


func MapSizeDecodeResponse(clientMessage *ClientMessage) func() ( /*** the number of key-value mappings in this map*/response int32) {
    return func() (/*** the number of key-value mappings in this map*/response int32) {
        iterator := clientMessage.FrameIterator()
        initialFrame := iterator.Next()
        response = DecodeInt(initialFrame.Content, MapSizeResponseResponseFieldOffset)
        return
    }
}

