
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
     "github.com/hazelcast/hazelcast-go-client/serialization"
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Applies the user defined EntryProcessor to the entries in the map which satisfies provided predicate.
 * Returns the results mapped by each key in the map.
 */
//@Generated("b9e7880c61b9f56ab6b4b02fb9daa506")
const (
    //hex: 0x013100
    MapExecuteWithPredicateRequestMessageType = 78080
    //hex: 0x013101
    MapExecuteWithPredicateResponseMessageType = 78081
    MapExecuteWithPredicateRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    MapExecuteWithPredicateResponseInitialFrameSize = CorrelationIdFieldOffset + IntSizeInBytes

)

func MapExecuteWithPredicateEncodeRequest(name string, entryProcessor serialization.Data, predicate serialization.Data) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Map.ExecuteWithPredicate")
	initialFrame := &Frame{Content: make([]byte, MapExecuteWithPredicateResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MapExecuteWithPredicateRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    DataCodecEncode(clientMessage, entryProcessor)


    DataCodecEncode(clientMessage, predicate)

    return clientMessage
}


func MapExecuteWithPredicateDecodeResponse(clientMessage *ClientMessage) func() (/*** results of entry process on the entries matching the query criteria*/response []*Pair) {
    return func() (/*** results of entry process on the entries matching the query criteria*/response []*Pair) {
        iterator := clientMessage.FrameIterator()
        //empty initial frame
        iterator.Next()
        var result []*Pair
        //begin frame, list
        iterator.Next()
        for !NextFrameIsDataStructureEndFrame(iterator) {
            i := 0
            key := DataCodecDecode(iterator)
            value := DataCodecDecode(iterator)
            result[i] = NewPair(key,value)
            i++
        }

        //end frame, list
        iterator.Next()
        response = result //2


        return
    }
}

