/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Queries the map based on the specified predicate and returns the matching entries.Specified predicate
 * runs on all members in parallel. The collection is NOT backed by the map, so changes to the map are NOT reflected
 * in the collection, and vice-versa. This method is always executed by a distributed query, so it may throw a
 * QueryResultSizeExceededException if query result size limit is configured.
 */
//@Generated("2232a44cabe45093a018eb86da68c1bc")
const (
    //hex: 0x012800
    MapEntriesWithPredicateRequestMessageType = 75776
    //hex: 0x012801
    MapEntriesWithPredicateResponseMessageType = 75777
    MapEntriesWithPredicateRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapEntriesWithPredicateResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEntriesWithPredicateRequestParameters struct {

    /**
    * name of map
    */
name string

    /**
    * specified query criteria.
    */
predicate bufutil.Data
}

func MapEntriesWithPredicateEncodeRequest(name string, predicate bufutil.Data) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = true
    clientMessage.SetOperationName("Map.EntriesWithPredicate")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapEntriesWithPredicateRequestMessageType)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, predicate)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEntriesWithPredicateResponseParameters struct {
    /**
    * result key-value entry collection of the query.
    */
response []*bufutil.Pair
}



func MapEntriesWithPredicateDecodeResponse(clientMessage *bufutil.ClientMessage) *MapEntriesWithPredicateResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapEntriesWithPredicateResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = var result []*bufutil.Pair
        //begin frame, list
        iterator.Next()
        for !bufutil.NextFrameIsDataStructureEndFrame(iterator) {
            i := 0
            key := bufutil.NoneCodecDecode(iterator))
            value := bufutil.NoneCodecDecode(iterator))
            result[i] = bufutil.NewPair(key,value)             i++
        }

        //end frame, list
        iterator.Next()
        response.response = result



    return response
}

