
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
     "github.com/hazelcast/hazelcast-go-client/serialization"
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Applies the user defined EntryProcessor to the all entries in the map.Returns the results mapped by each key in the map.
 */
//@Generated("33d3b45f14b644c84af431104ed6cbf0")
const (
    //hex: 0x013000
    MapExecuteOnAllKeysRequestMessageType = 77824
    //hex: 0x013001
    MapExecuteOnAllKeysResponseMessageType = 77825
    MapExecuteOnAllKeysRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    MapExecuteOnAllKeysResponseInitialFrameSize = CorrelationIdFieldOffset + IntSizeInBytes

)

func MapExecuteOnAllKeysEncodeRequest(name string, entryProcessor serialization.Data) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Map.ExecuteOnAllKeys")
	initialFrame := &Frame{Content: make([]byte, MapExecuteOnAllKeysResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MapExecuteOnAllKeysRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    DataCodecEncode(clientMessage, entryProcessor)

    return clientMessage
}


func MapExecuteOnAllKeysDecodeResponse(clientMessage *ClientMessage) func() (/*** results of entry process on the entries*/response []*Pair) {
    return func() (/*** results of entry process on the entries*/response []*Pair) {
        iterator := clientMessage.FrameIterator()
        //empty initial frame
        iterator.Next()
        var result []*Pair
        //begin frame, list
        iterator.Next()
        for !NextFrameIsDataStructureEndFrame(iterator) {
            i := 0
            key := DataCodecDecode(iterator)
            value := DataCodecDecode(iterator)
            result[i] = NewPair(key,value)
            i++
        }

        //end frame, list
        iterator.Next()
        response = result //2


        return
    }
}

