/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Tries to put the given key and value into this map within a specified timeout value. If this method returns false,
 * it means that the caller thread could not acquire the lock for the key within the timeout duration,
 * thus the put operation is not successful.
 */
//@Generated("15cb7e58dcc2a8f58a637c6c299f7f5b")
const (
    //hex: 0x010C00
    MapTryPutRequestMessageType = 68608
    //hex: 0x010C01
    MapTryPutResponseMessageType = 68609
    MapTryPutRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapTryPutRequestTimeoutFieldOffset = MapTryPutRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MapTryPutRequestInitialFrameSize = MapTryPutRequestTimeoutFieldOffset + bufutil.LongSizeInBytes
    MapTryPutResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    MapTryPutResponseInitialFrameSize = MapTryPutResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapTryPutRequestParameters struct {

    /**
    * Name of the map.
    */
name string

    /**
    * Key for the map entry.
    */
key serialization.Data

    /**
    * New value for the map entry.
    */
value serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * maximum time in milliseconds to wait for acquiring the lock for the key.
    */
timeout int64
}

func MapTryPutEncodeRequest(name string, key serialization.Data, value serialization.Data, threadId int64, timeout int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("Map.TryPut")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapTryPutRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MapTryPutRequestThreadIdFieldOffset, threadId)
    bufutil.EncodeLong(initialFrame.Content, MapTryPutRequestTimeoutFieldOffset, timeout)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    bufutil.DataCodecEncode(clientMessage, value)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapTryPutResponseParameters struct {
    /**
    * Returns true if successful, otherwise returns false
    */
response bool
}



func MapTryPutDecodeResponse(clientMessage *bufutil.ClientMessage) *MapTryPutResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapTryPutResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, MapTryPutResponseResponseFieldOffset)
    return response
}

