/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Releases the lock for the specified key. It never blocks and returns immediately.
 * If the current thread is the holder of this lock, then the hold count is decremented.If the hold count is zero,
 * then the lock is released.  If the current thread is not the holder of this lock,
 * then ILLEGAL_MONITOR_STATE is thrown.
 */
//@Generated("db01a59803b67fd34bdb00cfbe8c0e49")
const (
    //hex: 0x011300
    MapUnlockRequestMessageType = 70400
    //hex: 0x011301
    MapUnlockResponseMessageType = 70401
    MapUnlockRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapUnlockRequestReferenceIdFieldOffset = MapUnlockRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MapUnlockRequestInitialFrameSize = MapUnlockRequestReferenceIdFieldOffset + bufutil.LongSizeInBytes
    MapUnlockResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapUnlockRequestParameters struct {

    /**
    * name of map
    */
name string

    /**
    * Key for the map entry to unlock
    */
key serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * The client-wide unique id for this request. It is used to make the request idempotent by sending the same reference id during retries.
    */
referenceId int64
}

func MapUnlockEncodeRequest(name string, key serialization.Data, threadId int64, referenceId int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = true
    clientMessage.SetOperationName("Map.Unlock")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapUnlockRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MapUnlockRequestThreadIdFieldOffset, threadId)
    bufutil.EncodeLong(initialFrame.Content, MapUnlockRequestReferenceIdFieldOffset, referenceId)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapUnlockResponseParameters struct {
}



func MapUnlockDecodeResponse(clientMessage *bufutil.ClientMessage) *MapUnlockResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapUnlockResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

