/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Evicts the specified key from this map. If a MapStore is defined for this map, then the entry is not deleted
 * from the underlying MapStore, evict only removes the entry from the memory.
 */
//@Generated("b183c796cc87713caa81e5fb87f6e4d3")
const (
    //hex: 0x011E00
    MapEvictRequestMessageType = 73216
    //hex: 0x011E01
    MapEvictResponseMessageType = 73217
    MapEvictRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapEvictRequestInitialFrameSize = MapEvictRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MapEvictResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    MapEvictResponseInitialFrameSize = MapEvictResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEvictRequestParameters struct {

    /**
    * name of map
    */
name string

    /**
    * the specified key to evict from this map.
    */
key serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64
}

func MapEvictEncodeRequest(name string, key serialization.Data, threadId int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("Map.Evict")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapEvictRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MapEvictRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEvictResponseParameters struct {
    /**
    * true if the key is evicted, false otherwise.
    */
response bool
}



func MapEvictDecodeResponse(clientMessage *bufutil.ClientMessage) *MapEvictResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapEvictResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, MapEvictResponseResponseFieldOffset)
    return response
}

