
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes the given interceptor for this map so it will not intercept operations anymore.
 */
//@Generated("3ab24ca01e77b76bab068ec2ba80fc47")
const (
    //hex: 0x011500
    MapRemoveInterceptorRequestMessageType = 70912
    //hex: 0x011501
    MapRemoveInterceptorResponseMessageType = 70913
    MapRemoveInterceptorRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    MapRemoveInterceptorResponseResponseFieldOffset = CorrelationIdFieldOffset + IntSizeInBytes
    MapRemoveInterceptorResponseInitialFrameSize = MapRemoveInterceptorResponseResponseFieldOffset + BooleanSizeInBytes

)

func MapRemoveInterceptorEncodeRequest(name string, id string) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Map.RemoveInterceptor")
	initialFrame := &Frame{Content: make([]byte, MapRemoveInterceptorResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MapRemoveInterceptorRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    StringCodecEncode(clientMessage, id)

    return clientMessage
}


func MapRemoveInterceptorDecodeResponse(clientMessage *ClientMessage) func() (/*** Returns true if successful, otherwise returns false*/response bool) {
    return func() (/*** Returns true if successful, otherwise returns false*/response bool) {
        iterator := clientMessage.FrameIterator()
        initialFrame := iterator.Next()
        response = DecodeBoolean(initialFrame.Content, MapRemoveInterceptorResponseResponseFieldOffset)
        return
    }
}

