/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * TODO DOC
 */
//@Generated("54875f868e8a2dc94e89879571ecdc36")
const (
    //hex: 0x013600
    MapEntriesWithPagingPredicateRequestMessageType = 79360
    //hex: 0x013601
    MapEntriesWithPagingPredicateResponseMessageType = 79361
    MapEntriesWithPagingPredicateRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapEntriesWithPagingPredicateResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEntriesWithPagingPredicateRequestParameters struct {

    /**
    * name of map
    */
name string

    /**
    * specified query criteria.
    */
predicate serialization.Data
}

func MapEntriesWithPagingPredicateEncodeRequest(name string, predicate serialization.Data) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Map.EntriesWithPagingPredicate")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapEntriesWithPagingPredicateRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, predicate)
    return clientMessage
}

func MapEntriesWithPagingPredicateDecodeRequest(clientMessage *bufutil.ClientMessagex) *MapEntriesWithPagingPredicateRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MapEntriesWithPagingPredicateRequestParameters)
    //empty initial frame
    iterator.Next()
    request.name = StringCodec.decode(iterator)
    request.predicate = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapEntriesWithPagingPredicateResponseParameters struct {
    /**
    * key-value pairs for the query.
    */
response java.util.List<[]serialization.Data, []serialization.Data>
}

func MapEntriesWithPagingPredicateEncodeResponse(response []serialization.Data, []serialization.Data ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MapEntriesWithPagingPredicateResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapEntriesWithPagingPredicateResponseMessageType)
    clientMessage.Add(initialFrame)

    EntryListCodec.encode(clientMessage, response, DataCodecEncode, DataCodecEncode)
    return clientMessage
}

func MapEntriesWithPagingPredicateDecodeResponse(clientMessage *bufutil.ClientMessagex) *MapEntriesWithPagingPredicateResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapEntriesWithPagingPredicateResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = EntryListCodec.decode(iterator, DataCodecDecode, DataCodecDecode)
    return response
}

