/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes all entries which match with the supplied predicate
 */
//@Generated("a7d21e551e4ecddf84785f34a0f65dcb")
const (
    //hex: 0x014000
    MapRemoveAllRequestMessageType = 81920
    //hex: 0x014001
    MapRemoveAllResponseMessageType = 81921
    MapRemoveAllRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapRemoveAllResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapRemoveAllRequestParameters struct {

    /**
    * map name.
    */
name string

    /**
    * used to select entries to be removed from map.
    */
predicate serialization.Data
}

func MapRemoveAllEncodeRequest(name string, predicate serialization.Data) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Map.RemoveAll")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapRemoveAllRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, predicate)
    return clientMessage
}

func MapRemoveAllDecodeRequest(clientMessage *bufutil.ClientMessagex) *MapRemoveAllRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MapRemoveAllRequestParameters)
    //empty initial frame
    iterator.Next()
    request.name = StringCodec.decode(iterator)
    request.predicate = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapRemoveAllResponseParameters struct {
}

func MapRemoveAllEncodeResponse() *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MapRemoveAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapRemoveAllResponseMessageType)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func MapRemoveAllDecodeResponse(clientMessage *bufutil.ClientMessagex) *MapRemoveAllResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapRemoveAllResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

