/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Replaces the the entry for a key only if existing values equal to the testValue
 */
//@Generated("df599cba058d081dcd5e27a1f77e3e65")
const (
    //hex: 0x010500
    MapReplaceIfSameRequestMessageType = 66816
    //hex: 0x010501
    MapReplaceIfSameResponseMessageType = 66817
    MapReplaceIfSameRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapReplaceIfSameRequestInitialFrameSize = MapReplaceIfSameRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MapReplaceIfSameResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    MapReplaceIfSameResponseInitialFrameSize = MapReplaceIfSameResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapReplaceIfSameRequestParameters struct {

    /**
    * Name of the map.
    */
name string

    /**
    * Key for the map entry.
    */
key serialization.Data

    /**
    * Test the existing value against this value to find if equal to this value.
    */
testValue serialization.Data

    /**
    * New value for the map entry. Only replace with this value if existing value is equal to the testValue.
    */
value serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64
}

func MapReplaceIfSameEncodeRequest(name string, key serialization.Data, testValue serialization.Data, value serialization.Data, threadId int64) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Map.ReplaceIfSame")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapReplaceIfSameRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MapReplaceIfSameRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    DataCodec.encode(clientMessage, testValue)
    DataCodec.encode(clientMessage, value)
    return clientMessage
}

func MapReplaceIfSameDecodeRequest(clientMessage *bufutil.ClientMessagex) *MapReplaceIfSameRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MapReplaceIfSameRequestParameters)
    initialFrame := iterator.Next()
    request.threadId = bufutil.DecodeLong(initialFrame.Content, MapReplaceIfSameRequestThreadIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    request.testValue = DataCodec.decode(iterator)
    request.value = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapReplaceIfSameResponseParameters struct {
    /**
    * true if value is replaced with new one, false otherwise
    */
response bool
}

func MapReplaceIfSameEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MapReplaceIfSameResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapReplaceIfSameResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, MapReplaceIfSameResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func MapReplaceIfSameDecodeResponse(clientMessage *bufutil.ClientMessagex) *MapReplaceIfSameResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapReplaceIfSameResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, MapReplaceIfSameResponseResponseFieldOffset)
    return response
}

