/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Puts an entry into this map with a given ttl (time to live) value and maxIdle.
 * Entry will expire and get evicted after the ttl or maxIdle, whichever comes first.
 * If ttl and maxIdle are 0, then the entry lives forever.
 * 
 * Similar to the put operation except that set doesn't return the old value, which is more efficient.
 */
//@Generated("9d9426aa494936bdd913b30712aa99a8")
const (
    //hex: 0x014900
    MapSetWithMaxIdleRequestMessageType = 84224
    //hex: 0x014901
    MapSetWithMaxIdleResponseMessageType = 84225
    MapSetWithMaxIdleRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MapSetWithMaxIdleRequestTtlFieldOffset = MapSetWithMaxIdleRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MapSetWithMaxIdleRequestMaxIdleFieldOffset = MapSetWithMaxIdleRequestTtlFieldOffset + bufutil.LongSizeInBytes
    MapSetWithMaxIdleRequestInitialFrameSize = MapSetWithMaxIdleRequestMaxIdleFieldOffset + bufutil.LongSizeInBytes
    MapSetWithMaxIdleResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapSetWithMaxIdleRequestParameters struct {

    /**
    * Name of the map.
    */
name string

    /**
    * Key for the map entry.
    */
key serialization.Data

    /**
    * Value for the map entry.
    */
value serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * The duration in milliseconds after which this entry shall be deleted. O means infinite.
    */
ttl int64

    /**
    * The duration of maximum idle for this entry.
    * Milliseconds of idle, after which this entry shall be deleted. O means infinite.
    */
maxIdle int64
}

func MapSetWithMaxIdleEncodeRequest(name string, key serialization.Data, value serialization.Data, threadId int64, ttl int64, maxIdle int64) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Map.SetWithMaxIdle")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapSetWithMaxIdleRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MapSetWithMaxIdleRequestThreadIdFieldOffset, threadId)
    bufutil.EncodeLong(initialFrame.Content, MapSetWithMaxIdleRequestTtlFieldOffset, ttl)
    bufutil.EncodeLong(initialFrame.Content, MapSetWithMaxIdleRequestMaxIdleFieldOffset, maxIdle)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    DataCodec.encode(clientMessage, value)
    return clientMessage
}

func MapSetWithMaxIdleDecodeRequest(clientMessage *bufutil.ClientMessagex) *MapSetWithMaxIdleRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MapSetWithMaxIdleRequestParameters)
    initialFrame := iterator.Next()
    request.threadId = bufutil.DecodeLong(initialFrame.Content, MapSetWithMaxIdleRequestThreadIdFieldOffset)
    request.ttl = bufutil.DecodeLong(initialFrame.Content, MapSetWithMaxIdleRequestTtlFieldOffset)
    request.maxIdle = bufutil.DecodeLong(initialFrame.Content, MapSetWithMaxIdleRequestMaxIdleFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    request.value = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MapSetWithMaxIdleResponseParameters struct {
    /**
    * old value of the entry
    */
/* @Nullable */ response serialization.Data
}

func MapSetWithMaxIdleEncodeResponse(/* @Nullable */ response serialization.Data ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MapSetWithMaxIdleResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MapSetWithMaxIdleResponseMessageType)
    clientMessage.Add(initialFrame)

    CodecUtil.encodeNullable(clientMessage, response, DataCodecEncode)
    return clientMessage
}

func MapSetWithMaxIdleDecodeResponse(clientMessage *bufutil.ClientMessagex) *MapSetWithMaxIdleResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MapSetWithMaxIdleResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = CodecUtil.decodeNullable(iterator, DataCodecDecode) 
    return response
}

