/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes all the entries with the given key.
 */
//@Generated("9853185fd99f2938f73c4a20df637544")
const (
    //hex: 0x021600
    MultiMapDeleteRequestMessageType = 136704
    //hex: 0x021601
    MultiMapDeleteResponseMessageType = 136705
    MultiMapDeleteRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapDeleteRequestInitialFrameSize = MultiMapDeleteRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MultiMapDeleteResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapDeleteRequestParameters struct {

    /**
    * Name of the MultiMap
    */
name string

    /**
    * The key of the entry to remove
    */
key serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation
    */
threadId int64
}

func MultiMapDeleteEncodeRequest(name string, key serialization.Data, threadId int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("MultiMap.Delete")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapDeleteRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MultiMapDeleteRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapDeleteResponseParameters struct {
}



func MultiMapDeleteDecodeResponse(clientMessage *bufutil.ClientMessage) *MultiMapDeleteResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MultiMapDeleteResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

