/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the number of values that match the given key in the multimap.
 */
//@Generated("88b7f01dbe2ab90d1189fec7174ac300")
const (
    //hex: 0x020C00
    MultiMapValueCountRequestMessageType = 134144
    //hex: 0x020C01
    MultiMapValueCountResponseMessageType = 134145
    MultiMapValueCountRequestThreadIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapValueCountRequestInitialFrameSize = MultiMapValueCountRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    MultiMapValueCountResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapValueCountResponseInitialFrameSize = MultiMapValueCountResponseResponseFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapValueCountRequestParameters struct {

    /**
    * Name of the MultiMap
    */
name string

    /**
    * The key whose values count is to be returned
    */
key serialization.Data

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation
    */
threadId int64
}

func MultiMapValueCountEncodeRequest(name string, key serialization.Data, threadId int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = true
    clientMessage.SetOperationName("MultiMap.ValueCount")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapValueCountRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MultiMapValueCountRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapValueCountResponseParameters struct {
    /**
    * The number of values that match the given key in the multimap
    */
response int32
}



func MultiMapValueCountDecodeResponse(clientMessage *bufutil.ClientMessage) *MultiMapValueCountResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MultiMapValueCountResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeInt(initialFrame.Content, MultiMapValueCountResponseResponseFieldOffset)
    return response
}

