
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
     "github.com/hazelcast/hazelcast-go-client/serialization"
    "github.com/hazelcast/hazelcast-go-client/core"







)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds the specified entry listener for the specified key.The listener will be notified for all
 * add/remove/update/evict events for the specified key only.
 */
//@Generated("d6d8a55251b47e5d391cf1be764816d8")
const (
    //hex: 0x020D00
    MultiMapAddEntryListenerToKeyRequestMessageType = 134400
    //hex: 0x020D01
    MultiMapAddEntryListenerToKeyResponseMessageType = 134401
    MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset = PartitionIdFieldOffset + IntSizeInBytes
    MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset = MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset + BooleanSizeInBytes
    MultiMapAddEntryListenerToKeyRequestInitialFrameSize = MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset + BooleanSizeInBytes
    MultiMapAddEntryListenerToKeyResponseResponseFieldOffset = CorrelationIdFieldOffset + IntSizeInBytes
    MultiMapAddEntryListenerToKeyResponseInitialFrameSize = MultiMapAddEntryListenerToKeyResponseResponseFieldOffset + UUIDSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset = PartitionIdFieldOffset + IntSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset = MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset + IntSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset = MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset + UUIDSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryInitialFrameSize = MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset + IntSizeInBytes
    //hex: 0x020D02
    MultiMapAddEntryListenerToKeyEventEntryMessageType = 134402


)

func MultiMapAddEntryListenerToKeyEncodeRequest(name string, key serialization.Data, includeValue bool, localOnly bool) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("MultiMap.AddEntryListenerToKey")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MultiMapAddEntryListenerToKeyRequestMessageType)
    EncodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset, includeValue)
    EncodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset, localOnly)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    DataCodecEncode(clientMessage, key)

    return clientMessage
}


func MultiMapAddEntryListenerToKeyDecodeResponse(clientMessage *ClientMessage) func() (/*** Returns registration id for the entry listener*/response core.Uuid) {
    return func() (/*** Returns registration id for the entry listener*/response core.Uuid) {
        iterator := clientMessage.FrameIterator()
        initialFrame := iterator.Next()
        response = DecodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyResponseResponseFieldOffset)
        return
    }
}


type MultiMapAddEntryListenerToKeyHandleEntryFunc func(/* @Nullable */ key serialization.Data, /* @Nullable */ value serialization.Data, /* @Nullable */ oldValue serialization.Data, /* @Nullable */ mergingValue serialization.Data, eventType int32, uuid core.Uuid, numberOfAffectedEntries int32)

func MultiMapAddEntryListenerToKeyHandle(clientMessage *ClientMessage, handleEntry MultiMapAddEntryListenerToKeyHandleEntryFunc){
    messageType := clientMessage.MessageType()
    iterator := clientMessage.FrameIterator()
    if messageType == MultiMapAddEntryListenerToKeyEventEntryMessageType {
        initialFrame := iterator.Next()
        eventType := DecodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset)
        uuid := DecodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset)
        numberOfAffectedEntries := DecodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset)
        key := DecodeNullable(iterator, DataCodecDecode).(serialization.Data) // 2  

        value := DecodeNullable(iterator, DataCodecDecode).(serialization.Data) // 2  

        oldValue := DecodeNullable(iterator, DataCodecDecode).(serialization.Data) // 2  

        mergingValue := DecodeNullable(iterator, DataCodecDecode).(serialization.Data) // 2  

        handleEntry(key, value, oldValue, mergingValue, eventType, uuid, numberOfAffectedEntries)
        return
        }
        // FINEST: Logger.getLogger(super.getClass()).finest("Unknown message type received on event handler :" + messageType)
    }

