
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
    "github.com/hazelcast/hazelcast-go-client/serialization"
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Releases the lock for the specified key regardless of the lock owner. It always successfully unlocks the key,
 * never blocks and returns immediately.
 */
//@Generated("63645ad5a5963ceee158a50bdf39b70a")
const (
    //hex: 0x021400
    MultiMapForceUnlockRequestMessageType = 136192
    //hex: 0x021401
    MultiMapForceUnlockResponseMessageType = 136193
    MultiMapForceUnlockRequestReferenceIdFieldOffset = PartitionIdFieldOffset + IntSizeInBytes
    MultiMapForceUnlockRequestInitialFrameSize = MultiMapForceUnlockRequestReferenceIdFieldOffset + LongSizeInBytes
    MultiMapForceUnlockResponseInitialFrameSize = CorrelationIdFieldOffset + IntSizeInBytes

)

func MultiMapForceUnlockEncodeRequest(name string, key serialization.Data, referenceId int64) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( true )
    clientMessage.SetOperationName("MultiMap.ForceUnlock")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, MultiMapForceUnlockRequestMessageType)
    EncodeLong(initialFrame.Content, MultiMapForceUnlockRequestReferenceIdFieldOffset, referenceId)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    DataCodecEncode(clientMessage, key)

    return clientMessage
}


func MultiMapForceUnlockDecodeResponse(clientMessage *ClientMessage) func() () {
    return func() () {
        iterator := clientMessage.FrameIterator()
        //empty initial frame
        iterator.Next()
        return
    }
}

