/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds the specified entry listener for the specified key.The listener will be notified for all
 * add/remove/update/evict events for the specified key only.
 */
//@Generated("13f2fcd44cf0e5aa7a71df6c0bdc0f00")
const (
    //hex: 0x020D00
    MultiMapAddEntryListenerToKeyRequestMessageType = 134400
    //hex: 0x020D01
    MultiMapAddEntryListenerToKeyResponseMessageType = 134401
    MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset = MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset + bufutil.BooleanSizeInBytes
    MultiMapAddEntryListenerToKeyRequestInitialFrameSize = MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset + bufutil.BooleanSizeInBytes
    MultiMapAddEntryListenerToKeyResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapAddEntryListenerToKeyResponseInitialFrameSize = MultiMapAddEntryListenerToKeyResponseResponseFieldOffset + bufutil.UUIDSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset = MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset + bufutil.IntSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset = MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset + bufutil.UUIDSizeInBytes
    MultiMapAddEntryListenerToKeyEventEntryInitialFrameSize = MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset + bufutil.IntSizeInBytes
    //hex: 0x020D02
    MultiMapAddEntryListenerToKeyEventEntryMessageType = 134402


)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapAddEntryListenerToKeyRequestParameters struct {

    /**
    * Name of the MultiMap
    */
name string

    /**
    * The key to listen to
    */
key serialization.Data

    /**
    * True if EntryEvent should contain the value,false otherwise
    */
includeValue bool

    /**
    * if true fires events that originated from this node only, otherwise fires all events
    */
localOnly bool
}

func MultiMapAddEntryListenerToKeyEncodeRequest(name string, key serialization.Data, includeValue bool, localOnly bool) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("MultiMap.AddEntryListenerToKey")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapAddEntryListenerToKeyRequestMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset, includeValue)
    bufutil.EncodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset, localOnly)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    return clientMessage
}

func MultiMapAddEntryListenerToKeyDecodeRequest(clientMessage *bufutil.ClientMessagex) *MultiMapAddEntryListenerToKeyRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MultiMapAddEntryListenerToKeyRequestParameters)
    initialFrame := iterator.Next()
    request.includeValue = bufutil.DecodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestIncludeValueFieldOffset)
    request.localOnly = bufutil.DecodeBoolean(initialFrame.Content, MultiMapAddEntryListenerToKeyRequestLocalOnlyFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapAddEntryListenerToKeyResponseParameters struct {
    /**
    * Returns registration id for the entry listener
    */
response UUID
}

func MultiMapAddEntryListenerToKeyEncodeResponse(response UUID ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MultiMapAddEntryListenerToKeyResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapAddEntryListenerToKeyResponseMessageType)
    bufutil.EncodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func MultiMapAddEntryListenerToKeyDecodeResponse(clientMessage *bufutil.ClientMessagex) *MultiMapAddEntryListenerToKeyResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MultiMapAddEntryListenerToKeyResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyResponseResponseFieldOffset)
    return response
}

    func encodeMultiMapAddEntryListenerToKeyEvent(/* @Nullable */ key serialization.Data, /* @Nullable */ value serialization.Data, /* @Nullable */ oldValue serialization.Data, /* @Nullable */ mergingValue serialization.Data, eventType int, uuid UUID, numberOfAffectedEntries int) *bufutil.ClientMessagex {
        clientMessage := bufutil.createForEncode()
    	initialFrame := bufutil.Frame{make([]byte, MultiMapAddEntryListenerToKeyEventEntryInitialFrameSize), bufutil.UNFRAGMENTED_MESSAGE}
        initialFrame.flags |= ClientMessage.IS_EventFLAG
        bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapAddEntryListenerToKeyEventEntryMessageType)
        encodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset, eventType)
        encodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset, uuid)
        encodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset, numberOfAffectedEntries)
        clientMessage.Add(initialFrame)

        CodecUtil.encodeNullable(clientMessage, key, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, value, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, oldValue, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, mergingValue, DataCodecEncode)
        return clientMessage
    }

    type MultiMapAddEntryListenerToKeyAbstractEventItemFunc func(/* @Nullable */ key serialization.Data, /* @Nullable */ value serialization.Data, /* @Nullable */ oldValue serialization.Data, /* @Nullable */ mergingValue serialization.Data, eventType int, uuid UUID, numberOfAffectedEntries int)

     func MultiMapAddEntryListenerToKeyHandle(clientMessage *bufutil.ClientMessagex, handleEventItem MultiMapAddEntryListenerToKeyAbstractEventItemFunc){
        messageType := clientMessage.getMessageType()
        iterator := clientMessage.FrameIterator()
         if messageType == MultiMapAddEntryListenerToKeyEventEntryMessageType {
             initialFrame := iterator.Next()
             eventType := bufutil.DecodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryEventTypeFieldOffset)
             uuid := bufutil.DecodeUUID(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryUuidFieldOffset)
             numberOfAffectedEntries := bufutil.DecodeInt(initialFrame.Content, MultiMapAddEntryListenerToKeyEventEntryNumberOfAffectedEntriesFieldOffset)
             key := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             value := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             oldValue := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             mergingValue := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             handleEventItem(key, value, oldValue, mergingValue, eventType, uuid, numberOfAffectedEntries)
             return
          }
         Logger.getLogger(super.getClass()).finest("Unknown message type received on event handler :" + messageType)
     }

