/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Releases the lock for the specified key regardless of the lock owner. It always successfully unlocks the key,
 * never blocks and returns immediately.
 */
//@Generated("108967c7eaf1b0b362a063bbd2c66866")
const (
    //hex: 0x021400
    MultiMapForceUnlockRequestMessageType = 136192
    //hex: 0x021401
    MultiMapForceUnlockResponseMessageType = 136193
    MultiMapForceUnlockRequestReferenceIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    MultiMapForceUnlockRequestInitialFrameSize = MultiMapForceUnlockRequestReferenceIdFieldOffset + bufutil.LongSizeInBytes
    MultiMapForceUnlockResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapForceUnlockRequestParameters struct {

    /**
    * Name of the MultiMap
    */
name string

    /**
    * The key to Lock
    */
key serialization.Data

    /**
    * The client-wide unique id for this request. It is used to make the request idempotent by sending the same reference id during retries.
    */
referenceId int64
}

func MultiMapForceUnlockEncodeRequest(name string, key serialization.Data, referenceId int64) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("MultiMap.ForceUnlock")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapForceUnlockRequestMessageType)
    bufutil.EncodeLong(initialFrame.Content, MultiMapForceUnlockRequestReferenceIdFieldOffset, referenceId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    return clientMessage
}

func MultiMapForceUnlockDecodeRequest(clientMessage *bufutil.ClientMessagex) *MultiMapForceUnlockRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(MultiMapForceUnlockRequestParameters)
    initialFrame := iterator.Next()
    request.referenceId = bufutil.DecodeLong(initialFrame.Content, MultiMapForceUnlockRequestReferenceIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type MultiMapForceUnlockResponseParameters struct {
}

func MultiMapForceUnlockEncodeResponse() *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, MultiMapForceUnlockResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, MultiMapForceUnlockResponseMessageType)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func MultiMapForceUnlockDecodeResponse(clientMessage *bufutil.ClientMessagex) *MultiMapForceUnlockResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(MultiMapForceUnlockResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

