/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes the specified item listener.Returns silently if the specified listener was not added before.
 */
//@Generated("a75f77a12d03ee1f40c2f081e9d18b88")
const (
    //hex: 0x031200
    QueueRemoveListenerRequestMessageType = 201216
    //hex: 0x031201
    QueueRemoveListenerResponseMessageType = 201217
    QueueRemoveListenerRequestRegistrationIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    QueueRemoveListenerRequestInitialFrameSize = QueueRemoveListenerRequestRegistrationIdFieldOffset + bufutil.UUIDSizeInBytes
    QueueRemoveListenerResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    QueueRemoveListenerResponseInitialFrameSize = QueueRemoveListenerResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueRemoveListenerRequestParameters struct {

    /**
    * Name of the Queue
    */
name string

    /**
    * Id of the listener registration.
    */
registrationId UUID
}

func QueueRemoveListenerEncodeRequest(name string, registrationId UUID) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Queue.RemoveListener")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueRemoveListenerRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, QueueRemoveListenerRequestRegistrationIdFieldOffset, registrationId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func QueueRemoveListenerDecodeRequest(clientMessage *bufutil.ClientMessagex) *QueueRemoveListenerRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(QueueRemoveListenerRequestParameters)
    initialFrame := iterator.Next()
    request.registrationId = bufutil.DecodeUUID(initialFrame.Content, QueueRemoveListenerRequestRegistrationIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueRemoveListenerResponseParameters struct {
    /**
    * True if the item listener is removed, false otherwise
    */
response bool
}

func QueueRemoveListenerEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, QueueRemoveListenerResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueRemoveListenerResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, QueueRemoveListenerResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func QueueRemoveListenerDecodeResponse(clientMessage *bufutil.ClientMessagex) *QueueRemoveListenerResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(QueueRemoveListenerResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, QueueRemoveListenerResponseResponseFieldOffset)
    return response
}

