/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes all of this collection's elements that are also contained in the specified collection (optional operation).
 * After this call returns, this collection will contain no elements in common with the specified collection.
 */
//@Generated("252d52b2fcc133675c87e1fc2ace212f")
const (
    //hex: 0x030D00
    QueueCompareAndRemoveAllRequestMessageType = 199936
    //hex: 0x030D01
    QueueCompareAndRemoveAllResponseMessageType = 199937
    QueueCompareAndRemoveAllRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    QueueCompareAndRemoveAllResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    QueueCompareAndRemoveAllResponseInitialFrameSize = QueueCompareAndRemoveAllResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueCompareAndRemoveAllRequestParameters struct {

    /**
    * Name of the Queue
    */
name string

    /**
    * Collection containing elements to be removed from this collection
    */
dataList []serialization.Data
}

func QueueCompareAndRemoveAllEncodeRequest(name string, dataList []serialization.Data) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Queue.CompareAndRemoveAll")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueCompareAndRemoveAllRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    ListMultiFrameCodec.encode(clientMessage, dataList, DataCodecEncode)
    return clientMessage
}

func QueueCompareAndRemoveAllDecodeRequest(clientMessage *bufutil.ClientMessagex) *QueueCompareAndRemoveAllRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(QueueCompareAndRemoveAllRequestParameters)
    //empty initial frame
    iterator.Next()
    request.name = StringCodec.decode(iterator)
    request.dataList = ListMultiFrameCodec.decode(iterator, DataCodecDecode)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueCompareAndRemoveAllResponseParameters struct {
    /**
    * <tt>true</tt> if this collection changed as a result of the call
    */
response bool
}

func QueueCompareAndRemoveAllEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, QueueCompareAndRemoveAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueCompareAndRemoveAllResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, QueueCompareAndRemoveAllResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func QueueCompareAndRemoveAllDecodeResponse(clientMessage *bufutil.ClientMessagex) *QueueCompareAndRemoveAllResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(QueueCompareAndRemoveAllResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, QueueCompareAndRemoveAllResponseResponseFieldOffset)
    return response
}

