/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns true if this collection contains no elements.
 */
//@Generated("88f956eac67d96462b1d105abd2a33c4")
const (
    //hex: 0x031400
    QueueIsEmptyRequestMessageType = 201728
    //hex: 0x031401
    QueueIsEmptyResponseMessageType = 201729
    QueueIsEmptyRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    QueueIsEmptyResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    QueueIsEmptyResponseInitialFrameSize = QueueIsEmptyResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueIsEmptyRequestParameters struct {

    /**
    * Name of the Queue
    */
name string
}

func QueueIsEmptyEncodeRequest(name string) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("Queue.IsEmpty")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueIsEmptyRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func QueueIsEmptyDecodeRequest(clientMessage *bufutil.ClientMessagex) *QueueIsEmptyRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(QueueIsEmptyRequestParameters)
    //empty initial frame
    iterator.Next()
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type QueueIsEmptyResponseParameters struct {
    /**
    * <tt>True</tt> if this collection contains no elements
    */
response bool
}

func QueueIsEmptyEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, QueueIsEmptyResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, QueueIsEmptyResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, QueueIsEmptyResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func QueueIsEmptyDecodeResponse(clientMessage *bufutil.ClientMessagex) *QueueIsEmptyResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(QueueIsEmptyResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, QueueIsEmptyResponseResponseFieldOffset)
    return response
}

