
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Gets a lazy set view of the mappings contained in this map.
 */
//@Generated("dfe5e3565b9f22f56c4c0bbfa1d4a02e")
const (
    //hex: 0x0D1100
    ReplicatedMapEntrySetRequestMessageType = 856320
    //hex: 0x0D1101
    ReplicatedMapEntrySetResponseMessageType = 856321
    ReplicatedMapEntrySetRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    ReplicatedMapEntrySetResponseInitialFrameSize = CorrelationIdFieldOffset + IntSizeInBytes

)

func ReplicatedMapEntrySetEncodeRequest(name string) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( true )
    clientMessage.SetOperationName("ReplicatedMap.EntrySet")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, ReplicatedMapEntrySetRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)

    return clientMessage
}


func ReplicatedMapEntrySetDecodeResponse(clientMessage *ClientMessage) func() (/*** A lazy set view of the mappings contained in this map.*/response []*Pair) {
    return func() (/*** A lazy set view of the mappings contained in this map.*/response []*Pair) {
        iterator := clientMessage.FrameIterator()
        //empty initial frame
        iterator.Next()
        var result []*Pair
        //begin frame, list
        iterator.Next()
        for !NextFrameIsDataStructureEndFrame(iterator) {
            i := 0
            key := DataCodecDecode(iterator)
            value := DataCodecDecode(iterator)
            result[i] = NewPair(key,value)
            i++
        }

        //end frame, list
        iterator.Next()
        response = result //2


        return
    }
}

