/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds an entry listener for this map. The listener will be notified for all map add/remove/update/evict events.
 */
//@Generated("ea6a08abb29240453fd7c9c1a7e1d916")
const (
    //hex: 0x0D0D00
    ReplicatedMapAddEntryListenerRequestMessageType = 855296
    //hex: 0x0D0D01
    ReplicatedMapAddEntryListenerResponseMessageType = 855297
    ReplicatedMapAddEntryListenerRequestLocalOnlyFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ReplicatedMapAddEntryListenerRequestInitialFrameSize = ReplicatedMapAddEntryListenerRequestLocalOnlyFieldOffset + bufutil.BooleanSizeInBytes
    ReplicatedMapAddEntryListenerResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    ReplicatedMapAddEntryListenerResponseInitialFrameSize = ReplicatedMapAddEntryListenerResponseResponseFieldOffset + bufutil.UUIDSizeInBytes
    ReplicatedMapAddEntryListenerEventEntryEventTypeFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ReplicatedMapAddEntryListenerEventEntryUuidFieldOffset = ReplicatedMapAddEntryListenerEventEntryEventTypeFieldOffset + bufutil.IntSizeInBytes
    ReplicatedMapAddEntryListenerEventEntryNumberOfAffectedEntriesFieldOffset = ReplicatedMapAddEntryListenerEventEntryUuidFieldOffset + bufutil.UUIDSizeInBytes
    ReplicatedMapAddEntryListenerEventEntryInitialFrameSize = ReplicatedMapAddEntryListenerEventEntryNumberOfAffectedEntriesFieldOffset + bufutil.IntSizeInBytes
    //hex: 0x0D0D02
    ReplicatedMapAddEntryListenerEventEntryMessageType = 855298


)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ReplicatedMapAddEntryListenerRequestParameters struct {

    /**
    * Name of the ReplicatedMap
    */
name string

    /**
    * if true fires events that originated from this node only, otherwise fires all events
    */
localOnly bool
}

func ReplicatedMapAddEntryListenerEncodeRequest(name string, localOnly bool) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("ReplicatedMap.AddEntryListener")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ReplicatedMapAddEntryListenerRequestMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, ReplicatedMapAddEntryListenerRequestLocalOnlyFieldOffset, localOnly)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func ReplicatedMapAddEntryListenerDecodeRequest(clientMessage *bufutil.ClientMessagex) *ReplicatedMapAddEntryListenerRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(ReplicatedMapAddEntryListenerRequestParameters)
    initialFrame := iterator.Next()
    request.localOnly = bufutil.DecodeBoolean(initialFrame.Content, ReplicatedMapAddEntryListenerRequestLocalOnlyFieldOffset)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ReplicatedMapAddEntryListenerResponseParameters struct {
    /**
    * A unique string  which is used as a key to remove the listener.
    */
response UUID
}

func ReplicatedMapAddEntryListenerEncodeResponse(response UUID ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, ReplicatedMapAddEntryListenerResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ReplicatedMapAddEntryListenerResponseMessageType)
    bufutil.EncodeUUID(initialFrame.Content, ReplicatedMapAddEntryListenerResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func ReplicatedMapAddEntryListenerDecodeResponse(clientMessage *bufutil.ClientMessagex) *ReplicatedMapAddEntryListenerResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ReplicatedMapAddEntryListenerResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeUUID(initialFrame.Content, ReplicatedMapAddEntryListenerResponseResponseFieldOffset)
    return response
}

    func encodeReplicatedMapAddEntryListenerEvent(/* @Nullable */ key serialization.Data, /* @Nullable */ value serialization.Data, /* @Nullable */ oldValue serialization.Data, /* @Nullable */ mergingValue serialization.Data, eventType int, uuid UUID, numberOfAffectedEntries int) *bufutil.ClientMessagex {
        clientMessage := bufutil.createForEncode()
    	initialFrame := bufutil.Frame{make([]byte, ReplicatedMapAddEntryListenerEventEntryInitialFrameSize), bufutil.UNFRAGMENTED_MESSAGE}
        initialFrame.flags |= ClientMessage.IS_EventFLAG
        bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ReplicatedMapAddEntryListenerEventEntryMessageType)
        encodeInt(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryEventTypeFieldOffset, eventType)
        encodeUUID(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryUuidFieldOffset, uuid)
        encodeInt(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryNumberOfAffectedEntriesFieldOffset, numberOfAffectedEntries)
        clientMessage.Add(initialFrame)

        CodecUtil.encodeNullable(clientMessage, key, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, value, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, oldValue, DataCodecEncode)
        CodecUtil.encodeNullable(clientMessage, mergingValue, DataCodecEncode)
        return clientMessage
    }

    type ReplicatedMapAddEntryListenerAbstractEventItemFunc func(/* @Nullable */ key serialization.Data, /* @Nullable */ value serialization.Data, /* @Nullable */ oldValue serialization.Data, /* @Nullable */ mergingValue serialization.Data, eventType int, uuid UUID, numberOfAffectedEntries int)

     func ReplicatedMapAddEntryListenerHandle(clientMessage *bufutil.ClientMessagex, handleEventItem ReplicatedMapAddEntryListenerAbstractEventItemFunc){
        messageType := clientMessage.getMessageType()
        iterator := clientMessage.FrameIterator()
         if messageType == ReplicatedMapAddEntryListenerEventEntryMessageType {
             initialFrame := iterator.Next()
             eventType := bufutil.DecodeInt(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryEventTypeFieldOffset)
             uuid := bufutil.DecodeUUID(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryUuidFieldOffset)
             numberOfAffectedEntries := bufutil.DecodeInt(initialFrame.Content, ReplicatedMapAddEntryListenerEventEntryNumberOfAffectedEntriesFieldOffset)
             key := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             value := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             oldValue := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             mergingValue := CodecUtil.decodeNullable(iterator, DataCodecDecode) 
             handleEventItem(key, value, oldValue, mergingValue, eventType, uuid, numberOfAffectedEntries)
             return
          }
         Logger.getLogger(super.getClass()).finest("Unknown message type received on event handler :" + messageType)
     }

