/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Dispose the task from the scheduler
 */
//@Generated("0898c89bbd9543b7055f12bee8cd1d31")
const (
    //hex: 0x1A1200
    ScheduledExecutorDisposeFromAddressRequestMessageType = 1708544
    //hex: 0x1A1201
    ScheduledExecutorDisposeFromAddressResponseMessageType = 1708545
    ScheduledExecutorDisposeFromAddressRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    ScheduledExecutorDisposeFromAddressResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ScheduledExecutorDisposeFromAddressRequestParameters struct {

    /**
    * The name of the scheduler.
    */
schedulerName string

    /**
    * The name of the task
    */
taskName string

    /**
    * The address of the member where the task will get scheduled.
    */
address Address
}

func ScheduledExecutorDisposeFromAddressEncodeRequest(schedulerName string, taskName string, address Address) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = true
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("ScheduledExecutor.DisposeFromAddress")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ScheduledExecutorDisposeFromAddressRequestMessageType)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, schedulerName)
    StringCodec.encode(clientMessage, taskName)
    AddressCodec.encode(clientMessage, address)
    return clientMessage
}

func ScheduledExecutorDisposeFromAddressDecodeRequest(clientMessage *bufutil.ClientMessagex) *ScheduledExecutorDisposeFromAddressRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(ScheduledExecutorDisposeFromAddressRequestParameters)
    //empty initial frame
    iterator.Next()
    request.schedulerName = StringCodec.decode(iterator)
    request.taskName = StringCodec.decode(iterator)
    request.address = AddressCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type ScheduledExecutorDisposeFromAddressResponseParameters struct {
}

func ScheduledExecutorDisposeFromAddressEncodeResponse() *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, ScheduledExecutorDisposeFromAddressResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, ScheduledExecutorDisposeFromAddressResponseMessageType)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func ScheduledExecutorDisposeFromAddressDecodeResponse(clientMessage *bufutil.ClientMessagex) *ScheduledExecutorDisposeFromAddressResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(ScheduledExecutorDisposeFromAddressResponseParameters)
    //empty initial frame
    iterator.Next()
    return response
}

