
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
    "github.com/hazelcast/hazelcast-go-client/serialization"
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds all of the elements in the specified collection to this set if they're not already present
 * (optional operation). If the specified collection is also a set, the addAll operation effectively modifies this
 * set so that its value is the union of the two sets. The behavior of this operation is undefined if the specified
 * collection is modified while the operation is in progress.
 */
//@Generated("fe8a4f864daebe15b36ff9753c71285f")
const (
    //hex: 0x060600
    SetAddAllRequestMessageType = 394752
    //hex: 0x060601
    SetAddAllResponseMessageType = 394753
    SetAddAllRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    SetAddAllResponseResponseFieldOffset = CorrelationIdFieldOffset + IntSizeInBytes
    SetAddAllResponseInitialFrameSize = SetAddAllResponseResponseFieldOffset + BooleanSizeInBytes

)

func SetAddAllEncodeRequest(name string, valueList []serialization.Data) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Set.AddAll")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, SetAddAllRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    clientMessage.Add(BeginFrame)
        for i := 0; i < len(valueList) ; i++ {
            DataCodecEncode(clientMessage, valueList[i]) //check line
        }
        clientMessage.Add(EndFrame)



    return clientMessage
}


func SetAddAllDecodeResponse(clientMessage *ClientMessage) func() ( /*** True if this set changed as a result of the call*/response bool) {
    return func() (/*** True if this set changed as a result of the call*/response bool) {
        iterator := clientMessage.FrameIterator()
        initialFrame := iterator.Next()
        response = DecodeBoolean(initialFrame.Content, SetAddAllResponseResponseFieldOffset)
        return
    }
}

