
/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto



import (
    "github.com/hazelcast/hazelcast-go-client/serialization"
)


/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns true if this set contains the specified element.
 */
//@Generated("24494c81f9163cebc7204e6ae3d86e08")
const (
    //hex: 0x060200
    SetContainsRequestMessageType = 393728
    //hex: 0x060201
    SetContainsResponseMessageType = 393729
    SetContainsRequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes
    SetContainsResponseResponseFieldOffset = CorrelationIdFieldOffset + IntSizeInBytes
    SetContainsResponseInitialFrameSize = SetContainsResponseResponseFieldOffset + BooleanSizeInBytes

)

func SetContainsEncodeRequest(name string, value serialization.Data) *ClientMessage {
    clientMessage := CreateForEncode()
    clientMessage.SetRetryable( false )
    clientMessage.SetOperationName("Set.Contains")
	initialFrame := &Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: UnfragmentedMessage}
    EncodeInt(initialFrame.Content, TypeFieldOffset, SetContainsRequestMessageType)
    clientMessage.Add(initialFrame)

    StringCodecEncode(clientMessage, name)


    DataCodecEncode(clientMessage, value)

    return clientMessage
}


func SetContainsDecodeResponse(clientMessage *ClientMessage) func() ( /*** True if this set contains the specified element, false otherwise*/response bool) {
    return func() (/*** True if this set contains the specified element, false otherwise*/response bool) {
        iterator := clientMessage.FrameIterator()
        initialFrame := iterator.Next()
        response = DecodeBoolean(initialFrame.Content, SetContainsResponseResponseFieldOffset)
        return
    }
}

