/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Adds all of the elements in the specified collection to this set if they're not already present
 * (optional operation). If the specified collection is also a set, the addAll operation effectively modifies this
 * set so that its value is the union of the two sets. The behavior of this operation is undefined if the specified
 * collection is modified while the operation is in progress.
 */
//@Generated("78992488ed38f73708decb9d40744d4d")
const (
    //hex: 0x060600
    SetAddAllRequestMessageType = 394752
    //hex: 0x060601
    SetAddAllResponseMessageType = 394753
    SetAddAllRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    SetAddAllResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    SetAddAllResponseInitialFrameSize = SetAddAllResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type SetAddAllRequestParameters struct {

    /**
    * Name of the Set
    */
name string

    /**
    * Collection containing elements to be added to this set
    */
valueList []serialization.Data
}

func SetAddAllEncodeRequest(name string, valueList []serialization.Data) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("Set.AddAll")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, SetAddAllRequestMessageType)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    clientMessage.Add(bufutil.BeginFrame)
        for i := 0; i < len(valueList) ; i++ {
            bufutil.DataCodecEncode(clientMessage, valueList[i])
        }
        clientMessage.Add(bufutil.EndFrame)


    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type SetAddAllResponseParameters struct {
    /**
    * True if this set changed as a result of the call
    */
response bool
}



func SetAddAllDecodeResponse(clientMessage *bufutil.ClientMessage) *SetAddAllResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(SetAddAllResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, SetAddAllResponseResponseFieldOffset)
    return response
}

