/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Remove item from transactional set.
 */
//@Generated("93435aaa8697ae7e32ef0245b4a362cf")
const (
    //hex: 0x100200
    TransactionalSetRemoveRequestMessageType = 1049088
    //hex: 0x100201
    TransactionalSetRemoveResponseMessageType = 1049089
    TransactionalSetRemoveRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalSetRemoveRequestThreadIdFieldOffset = TransactionalSetRemoveRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalSetRemoveRequestInitialFrameSize = TransactionalSetRemoveRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalSetRemoveResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalSetRemoveResponseInitialFrameSize = TransactionalSetRemoveResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalSetRemoveRequestParameters struct {

    /**
    * Name of the Transactional Set
    */
name string

    /**
    * ID of the this transaction operation
    */
txnId UUID

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * Item removed from Transactional Set
    */
item serialization.Data
}

func TransactionalSetRemoveEncodeRequest(name string, txnId UUID, threadId int64, item serialization.Data) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("TransactionalSet.Remove")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalSetRemoveRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalSetRemoveRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalSetRemoveRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, item)
    return clientMessage
}

func TransactionalSetRemoveDecodeRequest(clientMessage *bufutil.ClientMessagex) *TransactionalSetRemoveRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(TransactionalSetRemoveRequestParameters)
    initialFrame := iterator.Next()
    request.txnId = bufutil.DecodeUUID(initialFrame.Content, TransactionalSetRemoveRequestTxnIdFieldOffset)
    request.threadId = bufutil.DecodeLong(initialFrame.Content, TransactionalSetRemoveRequestThreadIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.item = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalSetRemoveResponseParameters struct {
    /**
    * True if item is remove successfully
    */
response bool
}

func TransactionalSetRemoveEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, TransactionalSetRemoveResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalSetRemoveResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, TransactionalSetRemoveResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func TransactionalSetRemoveDecodeResponse(clientMessage *bufutil.ClientMessagex) *TransactionalSetRemoveResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalSetRemoveResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, TransactionalSetRemoveResponseResponseFieldOffset)
    return response
}

