/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the size of the list
 */
//@Generated("0cdedeeebbc5450a5637c3e52e01f5d1")
const (
    //hex: 0x110300
    TransactionalListSizeRequestMessageType = 1114880
    //hex: 0x110301
    TransactionalListSizeResponseMessageType = 1114881
    TransactionalListSizeRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalListSizeRequestThreadIdFieldOffset = TransactionalListSizeRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalListSizeRequestInitialFrameSize = TransactionalListSizeRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalListSizeResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalListSizeResponseInitialFrameSize = TransactionalListSizeResponseResponseFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalListSizeRequestParameters struct {

    /**
    * Name of the Transactional List
    */
name string

    /**
    * ID of the this transaction operation
    */
txnId UUID

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64
}

func TransactionalListSizeEncodeRequest(name string, txnId UUID, threadId int64) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("TransactionalList.Size")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalListSizeRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalListSizeRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalListSizeRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func TransactionalListSizeDecodeRequest(clientMessage *bufutil.ClientMessagex) *TransactionalListSizeRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(TransactionalListSizeRequestParameters)
    initialFrame := iterator.Next()
    request.txnId = bufutil.DecodeUUID(initialFrame.Content, TransactionalListSizeRequestTxnIdFieldOffset)
    request.threadId = bufutil.DecodeLong(initialFrame.Content, TransactionalListSizeRequestThreadIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalListSizeResponseParameters struct {
    /**
    * The size of the list
    */
response int
}

func TransactionalListSizeEncodeResponse(response int ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, TransactionalListSizeResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalListSizeResponseMessageType)
    bufutil.EncodeInt(initialFrame.Content, TransactionalListSizeResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func TransactionalListSizeDecodeResponse(clientMessage *bufutil.ClientMessagex) *TransactionalListSizeResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalListSizeResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeInt(initialFrame.Content, TransactionalListSizeResponseResponseFieldOffset)
    return response
}

