/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes all the entries associated with the given key.
 */
//@Generated("2ab60656420cd66e984e4669e1fa384e")
const (
    //hex: 0x0F0400
    TransactionalMultiMapRemoveEntryRequestMessageType = 984064
    //hex: 0x0F0401
    TransactionalMultiMapRemoveEntryResponseMessageType = 984065
    TransactionalMultiMapRemoveEntryRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalMultiMapRemoveEntryRequestThreadIdFieldOffset = TransactionalMultiMapRemoveEntryRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalMultiMapRemoveEntryRequestInitialFrameSize = TransactionalMultiMapRemoveEntryRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalMultiMapRemoveEntryResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalMultiMapRemoveEntryResponseInitialFrameSize = TransactionalMultiMapRemoveEntryResponseResponseFieldOffset + bufutil.BooleanSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMultiMapRemoveEntryRequestParameters struct {

    /**
    * Name of the Transactional Multi Map
    */
name string

    /**
    * ID of the this transaction operation
    */
txnId UUID

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * The key whose associated values are returned
    */
key serialization.Data

    /**
    * The value to be stored
    */
value serialization.Data
}

func TransactionalMultiMapRemoveEntryEncodeRequest(name string, txnId UUID, threadId int64, key serialization.Data, value serialization.Data) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("TransactionalMultiMap.RemoveEntry")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalMultiMapRemoveEntryRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalMultiMapRemoveEntryRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalMultiMapRemoveEntryRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    DataCodec.encode(clientMessage, key)
    DataCodec.encode(clientMessage, value)
    return clientMessage
}

func TransactionalMultiMapRemoveEntryDecodeRequest(clientMessage *bufutil.ClientMessagex) *TransactionalMultiMapRemoveEntryRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(TransactionalMultiMapRemoveEntryRequestParameters)
    initialFrame := iterator.Next()
    request.txnId = bufutil.DecodeUUID(initialFrame.Content, TransactionalMultiMapRemoveEntryRequestTxnIdFieldOffset)
    request.threadId = bufutil.DecodeLong(initialFrame.Content, TransactionalMultiMapRemoveEntryRequestThreadIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    request.key = DataCodec.decode(iterator)
    request.value = DataCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMultiMapRemoveEntryResponseParameters struct {
    /**
    * True if the size of the multimap changed after the remove operation, false otherwise.
    */
response bool
}

func TransactionalMultiMapRemoveEntryEncodeResponse(response bool ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, TransactionalMultiMapRemoveEntryResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalMultiMapRemoveEntryResponseMessageType)
    bufutil.EncodeBoolean(initialFrame.Content, TransactionalMultiMapRemoveEntryResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func TransactionalMultiMapRemoveEntryDecodeResponse(clientMessage *bufutil.ClientMessagex) *TransactionalMultiMapRemoveEntryResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalMultiMapRemoveEntryResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeBoolean(initialFrame.Content, TransactionalMultiMapRemoveEntryResponseResponseFieldOffset)
    return response
}

