/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Removes the given key value pair from the multimap.
 */
//@Generated("00e96bac7cd21d5dc16770ddf14736c1")
const (
    //hex: 0x0F0300
    TransactionalMultiMapRemoveRequestMessageType = 983808
    //hex: 0x0F0301
    TransactionalMultiMapRemoveResponseMessageType = 983809
    TransactionalMultiMapRemoveRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalMultiMapRemoveRequestThreadIdFieldOffset = TransactionalMultiMapRemoveRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalMultiMapRemoveRequestInitialFrameSize = TransactionalMultiMapRemoveRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalMultiMapRemoveResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMultiMapRemoveRequestParameters struct {

    /**
    * Name of the Transactional Multi Map
    */
name string

    /**
    * ID of the transaction
    */
txnId string

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * The key whose associated values are returned
    */
key serialization.Data
}

func TransactionalMultiMapRemoveEncodeRequest(name string, txnId string, threadId int64, key serialization.Data) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("TransactionalMultiMap.Remove")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalMultiMapRemoveRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalMultiMapRemoveRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalMultiMapRemoveRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    bufutil.DataCodecEncode(clientMessage, key)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMultiMapRemoveResponseParameters struct {
    /**
    * True if the size of the multimap changed after the remove operation, false otherwise.
    */
response []serialization.Data
}



func TransactionalMultiMapRemoveDecodeResponse(clientMessage *bufutil.ClientMessage) *TransactionalMultiMapRemoveResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalMultiMapRemoveResponseParameters)
    //empty initial frame
    iterator.Next()
    var result []serialization.Data
        //begin frame, list
        iterator.Next()
        for !bufutil.NextFrameIsDataStructureEndFrame(iterator) {
        result = append(result, bufutil.DataCodecDecode(iterator))
        }
        //end frame, list
        iterator.Next()
        response.response = result
    return response
}

