/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Returns the number of entries in this map.
 */
//@Generated("44496e9600c95df5dc1bc9fa0d70c7d8")
const (
    //hex: 0x0E0400
    TransactionalMapSizeRequestMessageType = 918528
    //hex: 0x0E0401
    TransactionalMapSizeResponseMessageType = 918529
    TransactionalMapSizeRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalMapSizeRequestThreadIdFieldOffset = TransactionalMapSizeRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalMapSizeRequestInitialFrameSize = TransactionalMapSizeRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalMapSizeResponseResponseFieldOffset = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalMapSizeResponseInitialFrameSize = TransactionalMapSizeResponseResponseFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMapSizeRequestParameters struct {

    /**
    * Name of the Transactional Map
    */
name string

    /**
    * ID of the this transaction operation
    */
txnId UUID

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64
}

func TransactionalMapSizeEncodeRequest(name string, txnId UUID, threadId int64) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("TransactionalMap.Size")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalMapSizeRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalMapSizeRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalMapSizeRequestThreadIdFieldOffset, threadId)
    clientMessage.Add(initialFrame)
    StringCodec.encode(clientMessage, name)
    return clientMessage
}

func TransactionalMapSizeDecodeRequest(clientMessage *bufutil.ClientMessagex) *TransactionalMapSizeRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(TransactionalMapSizeRequestParameters)
    initialFrame := iterator.Next()
    request.txnId = bufutil.DecodeUUID(initialFrame.Content, TransactionalMapSizeRequestTxnIdFieldOffset)
    request.threadId = bufutil.DecodeLong(initialFrame.Content, TransactionalMapSizeRequestThreadIdFieldOffset)
    request.name = StringCodec.decode(iterator)
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalMapSizeResponseParameters struct {
    /**
    * The number of entries in this map.
    */
response int
}

func TransactionalMapSizeEncodeResponse(response int ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, TransactionalMapSizeResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalMapSizeResponseMessageType)
    bufutil.EncodeInt(initialFrame.Content, TransactionalMapSizeResponseResponseFieldOffset, response)
    clientMessage.Add(initialFrame)

    return clientMessage
}

func TransactionalMapSizeDecodeResponse(clientMessage *bufutil.ClientMessagex) *TransactionalMapSizeResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalMapSizeResponseParameters)
    initialFrame := iterator.Next()
    response.response = bufutil.DecodeInt(initialFrame.Content, TransactionalMapSizeResponseResponseFieldOffset)
    return response
}

