/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto


import (
    "github.com/hazelcast/hazelcast-go-client/internal/proto/bufutil"
    "github.com/hazelcast/hazelcast-go-client/serialization"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * Retrieves, but does not remove, the head of this queue, or returns null if this queue is empty.
 */
//@Generated("bcda28d054cb3c5e217971953fb66eeb")
const (
    //hex: 0x120400
    TransactionalQueuePeekRequestMessageType = 1180672
    //hex: 0x120401
    TransactionalQueuePeekResponseMessageType = 1180673
    TransactionalQueuePeekRequestTxnIdFieldOffset = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    TransactionalQueuePeekRequestThreadIdFieldOffset = TransactionalQueuePeekRequestTxnIdFieldOffset + bufutil.UUIDSizeInBytes
    TransactionalQueuePeekRequestTimeoutFieldOffset = TransactionalQueuePeekRequestThreadIdFieldOffset + bufutil.LongSizeInBytes
    TransactionalQueuePeekRequestInitialFrameSize = TransactionalQueuePeekRequestTimeoutFieldOffset + bufutil.LongSizeInBytes
    TransactionalQueuePeekResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalQueuePeekRequestParameters struct {

    /**
    * Name of the Transactional Queue
    */
name string

    /**
    * ID of the transaction
    */
txnId string

    /**
    * The id of the user thread performing the operation. It is used to guarantee that only the lock holder thread (if a lock exists on the entry) can perform the requested operation.
    */
threadId int64

    /**
    * How long to wait before giving up, in milliseconds
    */
timeout int64
}

func TransactionalQueuePeekEncodeRequest(name string, txnId string, threadId int64, timeout int64) *bufutil.ClientMessage {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.Is_Retryable = false
    clientMessage.SetOperationName("TransactionalQueue.Peek")
	initialFrame := &bufutil.Frame{Content: make([]byte, ListAddAllResponseInitialFrameSize), Flags: bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, TransactionalQueuePeekRequestMessageType)
    bufutil.EncodeUUID(initialFrame.Content, TransactionalQueuePeekRequestTxnIdFieldOffset, txnId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalQueuePeekRequestThreadIdFieldOffset, threadId)
    bufutil.EncodeLong(initialFrame.Content, TransactionalQueuePeekRequestTimeoutFieldOffset, timeout)
    clientMessage.Add(initialFrame)
    bufutil.StringCodecEncode(clientMessage, name)
    return clientMessage
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type TransactionalQueuePeekResponseParameters struct {
    /**
    * The value at the head of the queue.
    */
/* @Nullable */ response serialization.Data
}



func TransactionalQueuePeekDecodeResponse(clientMessage *bufutil.ClientMessage) *TransactionalQueuePeekResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(TransactionalQueuePeekResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = bufutil.DecodeNullable(iterator, bufutil.DataCodecDecode).(serialization.Data)  
    return response
}

