/*
* Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License")
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package proto

import (
_"bytes"
"github.com/hazelcast/hazelcast-go-client/serialization"
_ "github.com/hazelcast/hazelcast-go-client"
)

/*
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
 */

/**
 * TODO DOC
 */
//@Generated("93a7ea5c4bea351eaf47d026a9cccb21")
const (
    //hex: 0x140200
    XATransactionCollectTransactionsRequestMessageType = 1311232
    //hex: 0x140201
    XATransactionCollectTransactionsResponseMessageType = 1311233
    XATransactionCollectTransactionsRequestInitialFrameSize = bufutil.PartitionIdFieldOffset + bufutil.IntSizeInBytes
    XATransactionCollectTransactionsResponseInitialFrameSize = bufutil.CorrelationIdFieldOffset + bufutil.IntSizeInBytes

)

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type XATransactionCollectTransactionsRequestParameters struct {
}

func XATransactionCollectTransactionsEncodeRequest() *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
    clientMessage.IsRetryable = false
    clientMessage.SetAcquiresResource(false)
    clientMessage.SetOperationName("XATransaction.CollectTransactions")
	initialFrame := bufutil.Frame{make([]byte, ListAddAllResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, XATransactionCollectTransactionsRequestMessageType)
    clientMessage.Add(initialFrame)
    return clientMessage
}

func XATransactionCollectTransactionsDecodeRequest(clientMessage *bufutil.ClientMessagex) *XATransactionCollectTransactionsRequestParameters {
    iterator := clientMessage.FrameIterator()
    request := new(XATransactionCollectTransactionsRequestParameters)
    //empty initial frame
    iterator.Next()
    return request
}

/* tslint:disabled:URF-UNREAD-PUBLIC-OR-PROTECTED-FIELD */
type XATransactionCollectTransactionsResponseParameters struct {
    /**
    * Array of Xids.
    */
response []Xid]
}

func XATransactionCollectTransactionsEncodeResponse(response Collection<javax.transaction.xa.Xid> ) *bufutil.ClientMessagex {
    clientMessage := bufutil.CreateForEncode()
	initialFrame := bufutil.Frame{make([]byte, XATransactionCollectTransactionsResponseInitialFrameSize), bufutil.UnfragmentedMessage}
    bufutil.EncodeInt(initialFrame.Content, bufutil.TypeFieldOffset, XATransactionCollectTransactionsResponseMessageType)
    clientMessage.Add(initialFrame)

    ListMultiFrameCodec.encode(clientMessage, response, XidCodecEncode)
    return clientMessage
}

func XATransactionCollectTransactionsDecodeResponse(clientMessage *bufutil.ClientMessagex) *XATransactionCollectTransactionsResponseParameters {
    iterator := clientMessage.FrameIterator()
    response := new(XATransactionCollectTransactionsResponseParameters)
    //empty initial frame
    iterator.Next()
    response.response = ListMultiFrameCodec.decode(iterator, XidCodecDecode)
    return response
}

