# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 2m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true


linters-settings:
  lll:
    line-length: 130

linters:
  enable:
    - deadcode
    - goimports
    - golint
    - ineffassign
    - interfacer
    - lll
    - misspell
    - unconvert
    - unparam
  disable-all: true


issues:
  exclude:
    - consts.go.*should have comment
    - .*DataOffset should have comment.*
    - .*TypePortable should have comment.*
    - .*LifecycleStateStarting should have comment.*
    - .*can be `fmt.Stringer`.*
    - .*WritePortable.*result.*is always `nil

  exclude-rules:
    - path: internal/proto
      linters:
        - deadcode
        - golint
        - lll
        - unconvert
        - unparam

    - path: sample/orgwebsite
      linters:
        - deadcode

    - path: internal/aggregation/aggregator_hook.go
      linters:
        - deadcode