apiVersion: v1
kind: Service
metadata:
  name: hz-go-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: hz-go-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hz-go-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hz-go-service
  template:
    metadata:
      labels:
        app: hz-go-service
    spec:
      containers:
        - name: hz-go-service
          image: example/hz-go-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
          livenessProbe: # prevents deadlock
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # prevents deadlock
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1

# Readiness probes indicate when an application is ready to serve traffic.
# If a readiness check fails then the container will be marked as not ready and will be removed from any load balancers.

# Liveness probes indicate a container is alive. If a liveness probe fails multiple times, then the container will be restarted.