package serialization


const(
	SQL_PREDICATE = 0
	AND_PREDICATE = 1
	BETWEEN_PREDICATE = 2
	EQUAL_PREDICATE = 3
	GREATERLESS_PREDICATE = 4
	LIKE_PREDICATE = 5
	ILIKE_PREDICATE = 6
	IN_PREDICATE = 7
	INSTANCEOF_PREDICATE = 8
	NOTEQUAL_PREDICATE = 9
	NOT_PREDICATE = 10
	OR_PREDICATE = 11
	REGEX_PREDICATE = 12
	FALSE_PREDICATE = 13
	TRUE_PREDICATE = 14
	PAGING_PREDICATE = 15
	PARTITION_PREDICATE = 16
	NULL_OBJECT = 17
)
