package serialization

const (
	CONSTANT_TYPE_NULL              = 0
	CONSTANT_TYPE_PORTABLE          = -1
	CONSTANT_TYPE_DATA_SERIALIZABLE = -2
	CONSTANT_TYPE_BYTE              = -3
	CONSTANT_TYPE_BOOLEAN           = -4
	CONSTANT_TYPE_CHAR              = -5
	CONSTANT_TYPE_SHORT             = -6
	CONSTANT_TYPE_INTEGER           = -7
	CONSTANT_TYPE_LONG              = -8
	CONSTANT_TYPE_FLOAT             = -9
	CONSTANT_TYPE_DOUBLE            = -10
	CONSTANT_TYPE_STRING            = -11
	CONSTANT_TYPE_BYTE_ARRAY        = -12
	CONSTANT_TYPE_BOOLEAN_ARRAY     = -13
	CONSTANT_TYPE_CHAR_ARRAY        = -14
	CONSTANT_TYPE_SHORT_ARRAY       = -15
	CONSTANT_TYPE_INTEGER_ARRAY     = -16
	CONSTANT_TYPE_LONG_ARRAY        = -17
	CONSTANT_TYPE_FLOAT_ARRAY       = -18
	CONSTANT_TYPE_DOUBLE_ARRAY      = -19
	CONSTANT_TYPE_STRING_ARRAY      = -20
	GO_DEFAULT_TYPE_GOB_SERIALIZER  = -100
)
