name: "Test Go Client with Race Detector Enabled"
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}"
      HZ_VERSION: "5.3.6"
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go_version: [ "1.20" ]
      fail-fast: false
    defaults:
      run:
        shell: "bash"
        working-directory: "$HOME/hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          path: "$HOME/hazelcast-go-client"

      - name: "Setup Go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "${{ matrix.go_version }}"

      - name: "Setup JRE"
        uses: "actions/setup-java@v2"
        with:
          distribution: "zulu"
          java-version: "8"

      - name: "Download RCD (Linux/MacOS)"
        if: "!contains(matrix.os, 'windows')"
        run: |
          wget https://rcd-download.s3.us-east-2.amazonaws.com/rcd-${{ matrix.os }}

      - name: "Start Hazelcast Remote Controller (Linux/MacOS)"
        if: "!contains(matrix.os, 'windows')"
        run: |
          chmod +x rcd-${{ matrix.os }} 
          ./rcd-${{ matrix.os }} -version $HZ_VERSION -dir $HOME &
          sleep 10

      - name: "Install Go tools"
        run: |
          go install golang.org/x/tools/...@v0.1.11
          go install honnef.co/go/tools/cmd/staticcheck@2022.1.2

      - name: "Go mod tidy"
        run: |
          go mod tidy

      - name: "Run Tests with Race Detection"
        run: |
          make test-race
