name: "Test Go Client with Race Detector Enabled"
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}"
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go_version: [ "1.20" ]
      fail-fast: false
    defaults:
      run:
        shell: "bash"
        working-directory: "hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v5"
        with:
          path: "hazelcast-go-client"

      - uses: ./hazelcast-go-client/.github/actions/build
        with:
          GO_VERSION: ${{ matrix.go_version }}
          OS: ${{ matrix.os }}

      - name: "Run Tests with Race Detection"
        run: |
          make test-race
